name: Daily Fixture Extraction

on:
  schedule:
    # This instructs the script to execute automatically every day at 12:00 PM UTC (adjust as needed!)
    - cron: '0 12 * * *'
  workflow_dispatch: # This adds a manual "Run now" button on the GitHub interface for testing

jobs:
  scrape-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Tools & Dependencies
        run: |
          pip install pandas undetected-chromedriver setuptools

      - name: Run Script
        run: python FullTimeFixtures.py

      - name: Save and Commit Updated CSV to Repository
        run: |
          git config --global user.name "GitHub Action Automation"
          git config --global user.email "actions@github.com"
          git add fixtures.csv
          # The "|| exit 0" prevents the script from crashing if no new fixtures were found today
          git commit -m "Automated update of youth football fixtures" || exit 0
          git push
